#define SETBIT(Word,Bit) Word |=(1<<Bit)
#define CLRBIT(Word,Bit) Word &=~(1<<Bit)
#define CPLBIT(Word,Bit) Word ^=(1<<Bit)
#define READBIT(Word,Bit) ((Word>>Bit)&1)
#define WRITEBIT(Word,BitPos,Bit) Word =((Word&~(1<<BitPos))|(Bit<<BitPos))
#define WRITENIBBLE(Word,BitStartPos,Val) Word =((Word&~(15<<BitStartPos))|(Val<<BitStartPos))
#define READNIBBLE(Word,BitStartPos) ((Word>>BitStartPos)&15)
#define WRITEBYTE(Word,BitStartPos,Val) Word =((Word&~(0xFFu<<BitStartPos))|(Val<<BitStartPos))
#define READBYTE(Word,BitStartPos) ((Word>>BitStartPos)&FF)
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
